export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const EDIT_ACCOUNT = 'EDIT_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const ADD_ACCOUNT_PRICE = 'ADD_ACCOUNT_PRICE';
export const SUB_ACCOUNT_PRICE = 'SUB_ACCOUNT_PRICE';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const ADD_TRANS = 'ADD_TRANS';
export const EDIT_TRANS = 'EDIT_TRANS';
export const DELETE_TRANS = 'DELETE_TRANS';
export const ADD_TRANSFER = 'ADD_TRANSFER';
export const EDIT_TRANSFER = 'EDIT_TRANSFER';
export const DELETE_TRANSFER = 'DELETE_TRANSFER';
